# Generated by Django 4.1.2 on 2023-01-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
